[package]
name = "polygraphia"
version = "0.1.0"
edition = "2024"
description = "A comprehensive library for classical and modern cryptographic algorithms."
license = "Apache-2.0"

[lib]
name = "polygraphia"
crate-type = ["rlib", "cdylib"]

[dependencies]
